version: '2'
services:
  db:
    image: mongo
  redis:
    image: redis
  web:
    build: ./app
    command: npm start
    volumes:
      - ./app:/code
    ports:
      - "3000:3000"
    environment:
      - SECRET=development-secret
      - MONGODB_HOST=db
      - REDIS_HOST=redis
      - GROUP_DOODLE_PORT=3000
    depends_on:
      - db
      - redis
